services:
  db:
    image: postgres:17
    container_name: mangareader_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MANGAPASSWORD
      POSTGRES_DB: MangaReaderDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: manga_api_container
    depends_on:
      - db                                     # So our API waits for the DB to be start first
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=MangaReaderDB;Username=postgres;Password=MANGAPASSWORD"
    ports:
      - "5000:80"

volumes:
  pgdata: